apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:cAOOhbRm6V2Hbuxg7DowmCaO3vaGmdFl9TtsNUtqqxg0sei8ca4i7/WxLz1qWkmiDEsdBDrzKSVkDfMcMxbLWAhR0YQPBMkm9ziV0wXzITVQ8DO1g2cUGnDwM6+IC3SQMbah,iv:TwFhdpBhCp3OKIpqWSqNrosyHKHWFs+2WpecawKdx98=,tag:ynbV3d8HrRUYoyjGbcGR2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T16:36:49Z"
    mac: ENC[AES256_GCM,data:QYYIbjZ+6wdh7PoCltdVRfifL9i5n5RMUaUoc6IZX/ySHHdmbkQD46e78PidPbLmMpcRLtu+2fLIkg89sM5xdi6PMxuP8lIi/luO8xwUgnRM1yCLhsUaquwE7JSGTetAZmWE2lzfsUHr9KzmCBTbP2H5pw5XPr3+a+wnx9ObkrQ=,iv:SSsF5E0DymAYaYjY2D/uaZ3vS4iBHku+ARsJpblx2is=,tag:KEUuYZHEeDUs7Z2iKVI5Wg==,type:str]
    pgp:
        - created_at: "2022-03-08T16:36:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA23ZLcABfhGjAQ//XFDGDd0uSUHJkg6EtHe3zRtne2zHKpkH8srXLAIm/j8W
            P8ZX+C9It/pfqDMGj/l2uBV/HnPT3a/PFkVJualC2yK3XkZudcxJGz3YcKEIAqZq
            N12cxhZpQQg4UCs9dtKB1QJGeeKaNx2owBE+s1yzunh+ddbZZhQ+AGxWFXtpQovP
            5CzV0hfexdBdObgPIQ5DHHpMut7/DHCavC0TnnSjJ7Npz7iM19BGCe2gAx+peKM9
            Th4MgXTmDu6oCRD6v4nM7DUWdOTnEDDc6kUaRtZgFzEh86ngcyQYjZajR3pzGMD9
            gIYw2c2EpwRKnmkF9c68XpmUYpVrs5o9hQXQXnZIgkDLWpxjbBHb7WrMQ1T/DX4H
            /lBVDM1fyCDgSUX/yVkLUFE+ONHOCSqHIVTwnLrKlLsaa42kJiQK7JvcFAP4s6NO
            l5EuQhtnIgxY1WFsrYJMzINuoHr/b+cXXvTE0c6uHi5Xo1GAJLBT79eMk5NXXjSN
            U+m8XRBGkrr73N/yq6QT/schUl1EfTGkbsbW3ycTaY+ykzo5CkmNkqqAZ3hrDdAn
            rnS7iB01qBlXZJ90v9pkK5uoR2UdxjYRaGBsDQJ8AWunLXmMRIXk3AY5zyGWqwLD
            DIRXaxC218/FCXByLDc6JAkwwnLjL8H2rn9U2tNhz4hlnFvkPn9r+awsxzpFi93S
            XgFm+9xj1q2BmTwZzYnxZNb7Tibibrq+BTMTyOcMdc+AWY9c5r9ctHa7fVIkIKfO
            13BSzSLhbJX51FuJSQDxSdMupwNT+u47kX6R10LDIkpvXchdfRRuhW64qrz1NOg=
            =S+dF
            -----END PGP MESSAGE-----
          fp: 386884E26D56934E51C068C464795BD1D551E348
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
